<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Instafake</title>

        <!-- Bootstrap -->
        <link href="../public/css/styles.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>
                            <i class="glyphicon glyphicon-camera"></i>
                            | Instafake
                        </h1>
                    </div>                    
                    <div class="col-sm-6 text-right">
                        <ul class="menu">
                            <li><a href="<?= site_url(); ?>" title="Home"><i class="glyphicon glyphicon-home"></i></a></li>
                            <li><a href="<?= make_url('usuario/perfil'); ?>" title="Perfil"><i class="glyphicon glyphicon-user"></i></a></li>
                            <li><a href="<?= make_url('usuario/logout'); ?>" title="Sair"><i class="glyphicon glyphicon-log-out"></i></a></li>
                        </ul>

                    </div>
                </div>
            </div><!-- /.container -->
        </header>

        <div class="container content">
            <div class="row">
                <h2>Seu perfil</h2>
                <p>Aqui você pode alterar suas informações ou sua senha.</p>
                <div class="perfil-form">
                    <form action="<?= make_url('usuario/update'); ?>" method="post" class="">
                        <div class="form-group">
                            <label for="nome">Nome</label>
                            <input type="text" class="form-control" name="nome" id="nome" required="required" placeholder="Nome completo" value="<?= $usuario->nome ?>"/>
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" name="email" id="email" required="required" placeholder="E-mail" value="<?= $usuario->email ?>"/>                                
                        </div>

                        <div class="form-group">
                            <label for="username">Nome de usuário</label>
                            <input type="text" class="form-control disabled" name="username" id="username" required="required" placeholder="Nome de usuário" value="<?= $usuario->username ?>" disabled="disabled"/>                                
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="password">Nova senha</label>
                                    <input type="password" class="form-control" name="password" id="password-cadastro" placeholder="Nova senha"/>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="confirmPassword">Confirmar senha</label>
                                    <input type="password" class="form-control" id="confirmPassword" placeholder="Confirmar senha"/>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="bnt btn-lg btn-primary">Atualizar</button>
                    </form>                
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="public/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            (function ($) {
                $(document).ready(function () {
                });
            })(jQuery)
        </script>
    </body>
</html>