<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Instafake</title>

        <!-- Bootstrap -->
        <link href="public/css/styles.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="login-page">
        <div class="container content">
            <div class="row">
                <div class="col-sm-6">
                    <img src="public/images/smartphone.png" alt="none" class="img-responsive hidden-xs"/>
                </div>

                <div class="col-sm-6 text-center">
                    <div class="box">
                        <h1>Instafake</h1>

                        <form action="./usuario/login" method="post">
                            <div class="form-group">
                                <input type="text" name="username" id="username" required="required" placeholder="Nome de usuário" />
                                <input type="password" name="password" id="password" required="required" placeholder="Senha" />
                                <button type="submit" class="btn btn-primary">Entrar</button>
                            </div>                            
                        </form>
                    </div><!-- .box -->

                    <div class="box">
                        <p>Não tem uma conta? <a href="#" data-toggle="modal" data-target="#cadastroModal">Cadastre-se</a></p>
                    </div><!-- .box -->

                </div>
            </div><!-- .row -->
        </div><!-- /.container -->

        <!-- Cadastro Modal -->
        <div class="modal fade" id="cadastroModal" tabindex="-1" role="dialog" aria-labelledby="cadastro">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form action="usuario/cadastro" method="post">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Cadastre-se</h4>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" name="nome" id="nome" required="required" placeholder="Nome completo"/>                                
                                <input type="email" name="email" id="email" required="required" placeholder="E-mail"/>                                
                                <input type="text" name="username" id="username" required="required" placeholder="Nome de usuário"/>                                
                                <input type="password" name="password" id="password-cadastro" required="required" placeholder="Sua senha"/>
                                <input type="password" id="confirmPassword" required="required" placeholder="Confirmar senha"/>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancelar</button>
                            <button id="submit-form" type="submit" class="btn btn-primary disabled" disabled="disabled">Cadastrar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="public/js/bootstrap.min.js"></script>
        <script type="text/javascript">
            (function($){
                $(document).ready(function(){
                   $('#confirmPassword').on('change keyup',function(){
                      if($(this).val() == $('#password-cadastro').val()){
                          $('#submit-form').attr('disabled',false).removeClass('disabled');
                          $(this).removeClass('error');
                      }else{
                          $(this).addClass('error');
                      }
                   });
                });
            })(jQuery)
        </script>
    </body>
</html>