<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Instafake</title>

        <!-- Bootstrap -->
        <link href="../public/css/styles.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1>
                            <i class="glyphicon glyphicon-camera"></i>
                            | Instafake
                        </h1>
                    </div>                    
                    <div class="col-sm-6 text-right">
                        <ul class="menu">
                            <li><a href="<?= site_url(); ?>" title="Home"><i class="glyphicon glyphicon-home"></i></a></li>
                            <li><a href="<?= make_url('usuario/perfil'); ?>" title="Perfil"><i class="glyphicon glyphicon-user"></i></a></li>
                            <li><a href="<?= make_url('usuario/logout'); ?>" title="Sair"><i class="glyphicon glyphicon-log-out"></i></a></li>
                        </ul>

                    </div>
                </div>
            </div><!-- /.container -->
        </header>

        <div class="container">
            <div class="row profile-info">
                <div class="col-sm-4 text-center">
                    <img src="<?= make_url('public/images/default-profile.png'); ?>" class="img-circle img-responsive profile-image" alt="<?= $p->nome ?>"/>
                </div>
                <div class="col-sm-8">
                    <h2>
                        <?= $p->nome ?> 
                        <?php if ($current_user): ?>
                            <a class="btn btn-default btn-lg" href="<?= make_url('usuario/editar') ?>">Editar perfil</a>
                        <?php else: ?>
                            <button title="marcação" class="btn btn-default">seguir</button>
                        <?php endif; ?>
                    </h2>

                    <div class="row counters">
                        <div class="col-sm-3">
                            <strong><?= $p->publicacoes ?></strong> publicações
                        </div>
                        <div class="col-sm-3">
                            <strong><?= $p->seguidores ?></strong> seguidores
                        </div>
                        <div class="col-sm-3">
                            seguindo <strong><?= $p->seguindo ?></strong>
                        </div>
                    </div>
                </div>
            </div>

            <?php if ($current_user): ?>
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3">
                        <form action="<?= make_url('post/add'); ?>" method="post" enctype="multipart/form-data">
                            <div class="panel panel-default">
                                <div class="panel-default share-form">

                                    <input type="file" id="foto" name="foto" class="hidden"/>
                                    <label for="foto" class="upload-foto text-center">  
                                        <div class="select">
                                            <i class="glyphicon glyphicon-camera"></i><br />
                                            <small>Compartilhe seu momento.</small>
                                        </div>                                
                                        <img id="preview" class="img-responsive preview hidden" src="" />
                                    </label>                            
                                    <textarea id="descricao" name="descricao" placeholder="Compartilhe seu momento!"></textarea>
                                </div>
                            </div>

                            <div class="text-right">
                                <button id="postar" type="submit" class="btn btn-primary disabled" disabled="disabled">Postar</button>
                            </div>
                        </form>
                    </div>
                </div>
            <?php endif; ?>

            <div class="posts">
                <div class="row">
                    <?php if ($posts) : ?>
                        <?php foreach ($posts as $post): ?>
                            <div class="col-sm-4 text-center post">
                                <div class="">
                                    <a class="load-post" href="#" data-toggle="modal" data-target="#postModal" data-post="<?= $post->id; ?>">
                                        <img src="<?= make_url('image/thumb?f=' . $post->foto) ?>" alt="<?= $post->descricao; ?>" class="img-responsive" />
                                        <div class="post-stats text-center">                                        
                                            <span class="post-counter">
                                                <i class="glyphicon glyphicon-heart"></i> <?= $post->curtidas_count ?>
                                            </span>
                                            <span class="post-counter">
                                                <i class="glyphicon glyphicon-comment"></i> <?= $post->comentarios_count ?>
                                            </span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        <?php endforeach; ?>

                        <!-- Post Modal -->
                        <div class="modal fade post-page" id="postModal" tabindex="-1" role="dialog" aria-labelledby="post">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">                                                                        
                                    <div class="modal-body">

                                    </div>                                        
                                    </form>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="<?= make_url('public/js/bootstrap.min.js'); ?>"></script>
        <script type="text/javascript">
            (function ($) {
                $(document).ready(function () {
                    $('#foto').change(function () {
                        readURL(this);
                        $('.select').addClass('hidden');
                        $('.preview').removeClass('hidden');

                        $('#postar').attr('disabled', false)
                                .removeClass('disabled');

                    });

                    function readURL(input) {
                        if (input.files && input.files[0]) {
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                $('#preview').attr('src', e.target.result);
                            }
                            reader.readAsDataURL(input.files[0]);
                        }
                    }

                    $('.load-post').click(function () {
                        var p = $(this).attr('data-post');

                        $.ajax({
                            url: '<?= make_url('post/page?p=') ?>' + p,
                            success: function (data) {
                                $('.modal-body').html(data);
                            }
                        });
                    });
                });
            })(jQuery)
        </script>
    </body>
</html>